### ISSUE TITLE
No module named `xmltodict`

### ISSUE THREAD

**Issue by florisvink** [datacoon/undatum#19]
There seem to be a missing dependancy when installed using `pip install --upgrade undatum`

```
➜  undatum --help
Traceback (most recent call last):
  File "/usr/local/bin/undatum", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/undatum/__main__.py", line 10, in main
    from .core import cli
  File "/usr/local/lib/python3.9/site-packages/undatum/core.py", line 9, in <module>
    from .cmds.analyzer import Analyzer
  File "/usr/local/lib/python3.9/site-packages/undatum/cmds/analyzer.py", line 13, in <module>
    import xmltodict
ModuleNotFoundError: No module named 'xmltodict'
```

After installing the dep manually (`pip install xmltodict`) it worked

**Comment by ivbeg** [comment]
Fixed in release 1.0.14, added xmltodict to requirements.txt and setup.py
